### ISSUE TITLE
Why are you running x86 instead os aarch64?

### ISSUE THREAD

**Issue by alex-morgun** [AntonyZ89/docker-qemu-arm#3]
Hello,

Just decided to test qemu on my tablet.

I am curious why does people decide to run docker in x86 instead of aarch64?

**Comment by AntonyZ89** [comment]
To be honest, I don't know. This repository was originated by another repository that was originated by a [gist](https://gist.github.com/oofnikj/e79aef095cd08756f7f26ed244355d62#file-docker-termux-md) ( 😆 lol) and in that gist the owner opted for x86 and commented it in the markdown:

![image](https://github.com/AntonyZ89/docker-qemu-arm/assets/1340674/ae4cf724-e7db-46e5-b378-d72c8d0c7d6d)

I've never tried other versions, I just follow things as they are, but these solutions originated in 2020, maybe today they can be executed better? I don't know

The author explained his point of view on why to use x86 instead of aarch64 here: [link](https://gist.github.com/oofnikj/e79aef095cd08756f7f26ed244355d62?permalink_comment_id=3591003#gistcomment-3591003)
